apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: aziz77/mysql:5.7
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: Fulldb
            - name: MYSQL_ROOT_PASSWORD
              value: system
          volumeMounts:
            - name: sql-volume
              mountPath: /var/lib/mysql
      volumes:
        - name: sql-volume
          hostPath:
              path: /home/aziz/data/sql
              type: Directory

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
